name: Deploy Shiny App

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      R_REPOS: https://cloud.r-project.org
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: false

      - name: Install rsconnect
        run: >
          R -q -e
          'install.packages(c("rsconnect","renv"), repos=Sys.getenv("R_REPOS"))'

      - name: Deploy to shinyapps.io
        run: >
          R -q -e
          'rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"),
          token=Sys.getenv("SHINYAPPS_TOKEN"),
          secret=Sys.getenv("SHINYAPPS_SECRET"));
          rsconnect::deployApp(appDir=".", forceUpdate=TRUE)'
